### model
model_name_or_path: Qwen/Qwen2-VL-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
# deepspeed: examples/deepspeed/ds_z3_config.json
resume_from_checkpoint: false
batch_eval_metrics: true
compute_iou: true

### dataset
dataset: action_localisation_train_factory_llama_vtimellm_50_epochs_fps4.0 # mllm_demo,identity  # video: mllm_video_demo
eval_dataset: challenge_action_localisation_valid_factory_llama_vtimellm_100_samples_tgr1.01_grouped_fps4.0
template: qwen2_vl
cutoff_len: 32768 #1024
overwrite_cache: false
tokenized_path: /pfss/mlde/workspaces/mlde_wsp_Rohrbach/data/raw/PerceptionTest/TokenizedLLaMA-Factory/50_epochs_fps_4_max_pixels_176400
preprocessing_num_workers: 32 # 4 gpus * 8 cpus per gpu = 32 vCPUs # 16 # TODO: tune to max GPU usage without getting CPU throttled # for dev / debug 1
preprocessing_batch_size: 16 # 2 # 1 # The number of examples in one group in pre-processing.
buffer_size: 2 # maybe per gpu?

video_resolution: 1024 # 128 # Keeps the height or width of video below this resolution.
video_fps: 4.0 # 2.0 # The frames to sample per second for video inputs.
video_maxlen: 768 # The maximum number of sampled frames for video inputs.
use_qwen2vl_processor: true
# total_pixels: 12845056 # 16384 * 28 * 28
max_pixels: 176400

### output
logging_steps: 5 # 10
save_steps: 50 # 1000 # 500 # lower for dev
plot_loss: true
# overwrite_output_dir: true

### train
flash_attn: fa2
#  ValueError: To use a `DataLoader` in `split_batches` mode, the batch size (2) needs to be a round multiple of the number of processes (4).
per_device_train_batch_size: 1 # 1
gradient_accumulation_steps: 4
learning_rate: 1.0e-4
# gradient steps? so to get 3 epochs,
# 1 per_device_train_batch_size * 2 gradient_accumulation_steps * 64 num_devices = 128 samples per step
# 2135 samples per epoch / 128 samples per step * 50 epochs wanted = 834 - seems tiny!
max_steps: 834
num_train_epochs: 1.00001873536
# max_steps: 1
# num_train_epochs: 0.002
# without split_batches, it fails to concatenate sequences of different lengths
# split_batches: true # ValueError: To use a `DataLoader` in `split_batches` mode, the batch size (2) needs to be a round multiple of the number of processes (4).
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 9000 # 180000000

### eval
val_size: 0 # 0.01 # Streaming mode should have an integer val size. # If you use a value different than 0, you get: `Cannot specify `val_size` if `eval_dataset` is not None.Cannot specify `val_size` if `eval_dataset` is not None.`
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 10 # 500 # lower for dev
#
# duplicate of eval_dataset + dataset_dir?
# task_dir: evaluation # not used by the HfArgumentParser #"Path to the folder containing the evaluation datasets.
# save_dir
seed: 42
# task: name of the evaluation task

report_to: wandb
run_name: 50epoch_lr1e-4_bs1_ga16_dsz3_warmup0.1_bs128_fps4_maxpixels176400_augData # optional
output_dir: output/qwen2_vl-7b/perception_test/action_localisation_vtimellm_50_epochs_lr1e-4_bs1_ga16_dsz3_warmup0.1_bs128_fps4_maxpixels176400_augData # must be given
deepspeed: examples/deepspeed/ds_z3_config.json
# run_name: create_data # optional
# output_dir: output/qwen2_vl-7b/perception_test/create_data
ddp_find_unused_parameters: false # `ddp_find_unused_parameters` needs to be set as False for LoRA in DDP training.
